name: Remote SSH Command

on:
  workflow_dispatch:

jobs:
  ssh_job:
    runs-on: ubuntu-latest

    steps:
      - name: Debug runner info
        run: |
          echo "HOME=$HOME"
          whoami
          ls -la $HOME

      - name: Set up SSH known_hosts
        run: |
          mkdir -p $HOME/.ssh
          ssh-keyscan -H 100.89.152.57 >> $HOME/.ssh/known_hosts
          chmod 644 $HOME/.ssh/known_hosts

      - name: Execute remote commands via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 100.89.152.57
          username: lumos
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "✅ Connected to Raspberry Pi via Tailscale!"
            hostname
            uptime
